### ISSUE TITLE
Error: Cannot find module 'meteor/mongo'

### ISSUE THREAD

**Issue by Hongbo-Miao** [dotansimha/angular2-meteor-with-observables#2]
The master branch will give the error below even I updated it to angular2-meteor  v0.6.3-beta.3.
(the ngrx branch works well)

> Error: Cannot find module 'meteor/mongo'

BTW, need remove .idea folder (from WebStorm)

**Comment by dotansimha** [comment]
Please try to update to the latest version of this repo, it will update your `package.json`, and then run `meteor npm install`, because I updated the commit id to the latest one.
