### ISSUE TITLE
Can not find module 'meteor/mongo'

### ISSUE THREAD

**Issue by jalalat** [dotansimha/angular2-meteor-with-observables#7]
when i try to run the app i get the following error: 

W20160831-00:15:50.849(1)? (STDERR) C:\Users\XPS\AppData\Local\.meteor\packages\meteor-tool\1.4.0\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:280
W20160831-00:15:51.369(1)? (STDERR)                                             throw(ex);
W20160831-00:15:51.373(1)? (STDERR)                                             ^
W20160831-00:15:51.383(1)? (STDERR)
W20160831-00:15:51.386(1)? (STDERR) Error: Cannot find module 'meteor/mongo'
W20160831-00:15:51.389(1)? (STDERR)     at Function.Module._resolveFilename (module.js:325:15)
W20160831-00:15:51.395(1)? (STDERR)     at Function.Module._load (module.js:276:25)
W20160831-00:15:51.401(1)? (STDERR)     at Module.require (module.js:353:17)
W20160831-00:15:51.406(1)? (STDERR)     at require (internal/module.js:12:17)
W20160831-00:15:51.414(1)? (STDERR)     at Object.<anonymous> (C:\projects\angular2-meteor-with-observables-master\node_modules\angular2-meteor\dist\minimongo-observable\observable-collection.js:2:15)
W20160831-00:15:51.427(1)? (STDERR)     at Module._compile (module.js:409:26)
W20160831-00:15:51.431(1)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)
W20160831-00:15:51.437(1)? (STDERR)     at Module.load (module.js:343:32)
W20160831-00:15:51.445(1)? (STDERR)     at Module.Mp.load (C:\Users\XPS\AppData\Local\.meteor\packages\babel-compiler\6.9.0\npm\node_modules\reify\node\runtime.js:16:23)
W20160831-00:15:51.451(1)? (STDERR)     at Function.Module._load (module.js:300:12)

**Comment by dotansimha** [comment]
I was already fixed.. please try to update to the latest version of angular2-meteor

**Comment by jalalat** [comment]
Hi, Thanks it worked. I thought the package.json was changed as someone already reported the same issue a month ago and it was closed.

Can we please change the package.json file to use this version     "angular2-meteor": "^0.6.3-beta.5".
