### ISSUE TITLE
breaking collection2

### ISSUE THREAD

**Issue by jalalat** [dotansimha/angular2-meteor-with-observables#8]
I can not attach Schema using Collection2 [https://github.com/aldeed/meteor-collection2]

> 
> W20160831-15:09:11.512(1)? (STDERR) C:\Users\XPS\AppData\Local\.meteor\packages\meteor-tool\1.4.0-1\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:280
> W20160831-15:09:11.827(1)? (STDERR)                                             throw(ex);
> W20160831-15:09:11.836(1)? (STDERR)                                             ^
> W20160831-15:09:11.844(1)? (STDERR)
> W20160831-15:09:11.852(1)? (STDERR) TypeError: exports.Notifications.attachSchema is not a function
> W20160831-15:09:11.860(1)? (STDERR)     at meteorInstall.both.collections.notifications.notifications.collection.js (both/collections/notifications/notifications.collection.ts:22:15)
> W20160831-15:09:11.881(1)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
> W20160831-15:09:11.891(1)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
> W20160831-15:09:11.901(1)? (STDERR)     at server/main.ts:16:4
> W20160831-15:09:11.909(1)? (STDERR)     at C:\projects\bakbak24\.meteor\local\build\programs\server\boot.js:297:10
> W20160831-15:09:11.918(1)? (STDERR)     at Array.forEach (native)
> W20160831-15:09:11.926(1)? (STDERR)     at Function._.each._.forEach (C:\Users\XPS\AppData\Local\.meteor\packages\meteor-tool\1.4.0-1\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
> W20160831-15:09:11.947(1)? (STDERR)     at C:\projects\bakbak24\.meteor\local\build\programs\server\boot.js:133:5

My code is 

```
import { MongoObservable } from 'angular2-meteor';
import { Notification, NotificationSchema, NotificationsPublicFields } from './notifications.interface';

class NotificationsCollection extends MongoObservable.Collection < Notification > {
	
}

export let Notifications: any = new NotificationsCollection('notifications');

Notifications.deny({
    insert() {
        return true;
    },
    update() {
        return true;
    },
    remove() {
        return true;
    },
});

Notifications.attachSchema(NotificationSchema);
Notifications.publicFields = NotificationsPublicFields;
```

**Comment by dotansimha** [comment]
Hi @jalalat ,

Please use `Notifications.getMongoCollection()` API to get the actual collection, which has `attachSchema` method.
